version: "3"

services:
  cool-ui:
    build: ./cool-ui
    ports:
      - "80:80"
    networks:
      - front-tier
      - back-tier

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - "db-data:/var/lib/db"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
