version: "3"

services:
  cool-ui:
    build: ./cool-ui
    ports:
      - "80:80"
    networks:
      - front-tier
      - back-tier

  server:
    build: ./server
    ports:
      - "3000:3000"
    networks:
      - back-tier
networks:
  front-tier:
  back-tier:
